version: '3.5'
services:
  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ..:/var/www/app
      #- /etc/localtime:/etc/localtime:ro
    depends_on:
      - rails
  rails:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: bundle exec pumactl start
    ports:
      - '3000:3000'
    volumes:
      - ..:/var/www/app
      #- /etc/localtime:/etc/localtime:ro

